name: "Jira Validations"
description: "Verify PR/Push has required Jira Info"
inputs:
  verify-from: # id of input
    description: "Where to verify Jira Issue IDs. Can be 'branch', 'commits' or 'all'"
    required: true
    default: "branch"
  fail-invalid: # id of input
    description: "Describe how to fail if we have an invalid Jira ID. Can be 'true', or 'false'"
    required: true
    default: "true"
  allowed-issue-types: # id of input
    description: "Allowed Issue Types, comma separated, can be 'Task,Standalone Task,Bug'"
    required: true
    default: "Task,Standalone Task,Bug,Technical Innovation,Product Innovation,Technical Debt"
outputs:
  verified: # id of output
    description: "Will be 'true' if it passed all checks, 'false' otherwise"
runs:
  using: "node12"
  main: "dist/index.js"
