name: Validate PR
on: [pull_request]

jobs:
  validate_pr_job:
    runs-on: ubuntu-latest
    name: Validate Jira PR

    steps:
      - name: Validate Jira step
        id: jira-pr
        uses: rigup/jira-validations@master
        with:
          verify-from: "all"
          fail-invalid: "true"
          allowed-issue-types: "Task,Standalone Task,Bug"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          PEOPLE_TABLE_NAME: ${{ secrets.PEOPLE_TABLE_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Use the output from the `jira` step
      - name: Get the output
        run: echo "Verified ${{ steps.jira-pr.outputs.verified }}"
