on: [push]

jobs:
  validate_job:
    runs-on: ubuntu-latest
    name: A job
    steps:
    - name: Validate Jira step
      id: jira
      uses: rigup/jira-validations@master
      with:
        verify-from: 'branch'
        fail-invalid: 'false'
    # Use the output from the `jira` step
    - name: Get the output 
      run: echo "The time was ${{ steps.jira.outputs.verified }}"
